import { User } from '../../../../../../MyApplication/entry/src/main/ets/common/type'

export let usersData: User[] = [
    new User('张三', $r('app.media.startIcon')),
    new User('李四', $r('app.media.startIcon')),
    new User('王五', $r('app.media.startIcon')),
    new User('赵六', $r('app.media.startIcon')),
    new User('刘禾', $r('app.media.startIcon')),
    new User('爱国', $r('app.media.startIcon')),
    new User('爱民', $r('app.media.startIcon')),
    new User('阳阳', $r('app.media.startIcon')),
    new User('小明', $r('app.media.startIcon')),
    new User('小红', $r('app.media.startIcon')),
  ]

